config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :posts do
    resources :comments
  end

	root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/mymailer.rb
class MyMailer < Devise::Mailer   
  helper :application # gives access to all helpers defined within `application_helper`.
  include Devise::Controllers::UrlHelpers # Optional. eg. `confirmation_url`
  default template_path: 'devise/mailer' # to make sure that your mailer uses the devise views
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # def after_sign_in_path_for(resource)
  #   current_user_path
  # end
  #
  # def after_sign_out_path_for(resource_or_scope)
  #   request.referrer
  # end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController



  def create
    @post=Post.find(permited_params[:post_id])
    @comment=@post.comments.create(permited_params[:comment])
    @comment.user = current_user if current_user

    if @comment.save!
      redirect_to post_path(@post)
    else
    end
  end

  def edit
    post
  end

  def update
    # post
    if comment.update(params[:comment].permit(:comment))
      redirect_to post_path(post)
    else
      render 'edit'
    end
  end

  def destroy
    comment.destroy
    redirect_to post_path(@post)
  end

  private
  def permited_params
    params.permit(:id, :post_id, :comment)
  end

  def comment
    @comment= Comment.find(permited_params[:id])
  end

  def post
    @post = comment.post
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts=Post.all.order("created_at DESC")
	end
	
	def new
		@post=current_user.posts.build
	end

	def create
		@post=current_user.posts.build(post_params)
		if @post.save
			redirect_to @post
		else
			render "new"
		end
	end

	def show
	end

	def destroy
		@post.destroy
			redirect_to root_path
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end


	private

	def find_post
		@post=Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .content
    %p.comment_content= comment.comment
    %p.comment_author= comment.user.email
  .buttons
    - if user_signed_in?
      = link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: {confirm: "Are you sure?"}
      = link_to "Edit", edit_post_comment_path(comment.post, comment)

app/views/comments/_form.html.haml
= simple_form_for ([@post, @post.comments.build]) do |f|
  - if user_signed_in?
    = f.input :comment
    = f.submit
  - else
    = f.input :comment
    = link_to 'Sign_up', new_user_registration_path, class: "button"

app/views/comments/edit.html.haml
%h1 Edit Form

#edit_comment_form
  = simple_form_for ([@post, @comment]) do |f|
    = f.input :comment
    = f.submit 'Update'
    = link_to 'Cancel', post_path(@post),class: "link_cancel"

app/views/layouts/application.html.haml
%html
%head
	%title JokOotk
	%link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css"}/
	%link{:rel => "stylesheet", :href => "https://fonts.googleapis.com/css?family=Lato:300,400,700,900"}/
	= csrf_meta_tags
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
	%header.main_header.clearfix
		.wrapper
			#logo
				%p=link_to "JokOotk", root_path
			.buttons
				- if user_signed_in?
					=link_to 'New Post', new_post_path
					=link_to 'Out', destroy_user_session_path, method: :delete
				- else
					=link_to 'Sign_up', new_user_registration_path
					=link_to 'Sign_in', new_user_session_path
	.wrapper
		%p.notice= notice
		%p.alert= alert
	.wrapper
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title, class: "form_title"
  = f.input :content, class: "form_descr"
  = f.submit

app/views/posts/edit.html.haml
%h1 Edit
#form_container
  =render 'form'
  = link_to 'Back', post_path(@post), class: "link_back"

app/views/posts/index.html.haml
#posts
	- @posts.each do |post|
		.post
			%h2.title=link_to post.title, post
			%p.date 
				Published at
				= time_ago_in_words(post.created_at)
				by
				= post.user_id

app/views/posts/new.html.haml
%h1 New Post
#form_container
  = render 'form'
  = link_to 'Back', root_path, class: "link_back"

app/views/posts/show.html.haml
#post_content
  %h2= @post.title
  %p= @post.content

  #comments
    %h2
    = @post.comments.count
    Comments
    = render @post.comments
    = render 'comments/form'

  %hr/
  %br/
  
  - if user_signed_in?
    =link_to 'Edit', edit_post_path(@post), class: "button"
    =link_to 'Delete', post_path(@post), method: :Delete, data: {confirm: 'Are you sure?'}, class: "button"
    =link_to 'Home', root_path, class: "button"

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>